export { FECHAS_ORDINARIAS, INICIO_DEL_PERIODO } from './config'
export type { Afiliado, Declaracion } from './modelos'
export { fechasOrdinariasDelPeriodo, periodoDe } from './periodos'
export type { Afiliacion } from './publico'
export { validarFecha } from './validaciones'
